# Generated by Django 4.2.28 on 2026-03-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciseresult",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
