# Generated by Django 4.2.28 on 2026-04-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0003_achievement_childachievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciseresult",
            name="completeness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="fluency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="recognized_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exerciseresult",
            name="weak_phonemes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
