# Generated by Django 4.2.28 on 2026-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
