# Generated by Django 4.2.28 on 2026-03-16 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_childprofile_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
