# Generated by Django 4.2.28 on 2026-03-22 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_childprofile_user_alter_childprofile_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childprofile",
            name="difficulty_level",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")],
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
