# Generated by Django 4.2.28 on 2026-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_childprofile_difficulty_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
