# Generated by Django 4.2.28 on 2026-03-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("word", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="exercises/images/")),
                ("audio_file", models.FileField(upload_to="exercises/audio/")),
                ("passing_score", models.PositiveSmallIntegerField(default=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
