# Generated by Django 4.2.28 on 2026-03-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="type",
            field=models.CharField(
                choices=[("word", "Word"), ("sound", "Sound")],
                default="word",
                max_length=10,
            ),
        ),
    ]
