# Generated by Django 4.2.28 on 2026-03-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("difficulty", models.PositiveSmallIntegerField(default=1)),
                (
                    "age_category",
                    models.CharField(
                        choices=[
                            ("2-3", "2-3 years"),
                            ("4-5", "4-5 years"),
                            ("6-7", "6-7 years"),
                        ],
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercises",
                    models.ManyToManyField(
                        related_name="lessons", to="exercises.exercise"
                    ),
                ),
            ],
        ),
    ]
