# Generated by Django 4.2.28 on 2026-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
