# Generated by Django 4.2.28 on 2026-03-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_lesson_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="difficulty",
        ),
    ]
