# Generated by Django 4.2.28 on 2026-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_remove_lesson_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lessons/images/"),
        ),
    ]
