name: Backend CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: speech_therapy.settings

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - run: |
          pip install -r requirements.txt
          pip install pylint pylint-django flake8 celery

      - run: |
          pylint --load-plugins=pylint_django \
                 --django-settings-module=speech_therapy.settings \
                 --ignore=migrations,venv \
                 speech_therapy

      - run: |
          flake8 --max-line-length=120 --exclude=migrations,venv speech_therapy


  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: speech_therapy.settings

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - run: |
          pip install -r requirements.txt

      - run: |
          python manage.py migrate

      - run: |
          pytest
